### ISSUE TITLE
Hebrew Support

### ISSUE THREAD

**Issue by bsagal** [source-foundry/Hack#221] opened 2016-08-03 07:29 UTC
Please can you add hebrew glyphs.

**Comment by chrissimpkins** [comment] 2017-07-07 15:47
Noted.  Thanks for the suggestion.

**Comment by funkyfuture** [comment] 2017-08-15 17:01
actually a duplicate of #47.

**Closed** 2017-08-15 17:18 UTC
Labels: Character Set, enhancement

**Comment by chrissimpkins** [comment] 2017-08-15 17:49
thanks!
