### ISSUE TITLE
U+1E9E - consider addition to character sets

### ISSUE THREAD

**Issue by Bogbo** [source-foundry/Hack#239] opened 2017-01-19 10:53 UTC
Could you please add U+1E9E (Capital Letter Sharp ß)? Thank you!

**Comment by xelra** [comment] 2017-02-17 12:18
Are you sure you want [Unicode Character 'LATIN CAPITAL LETTER SHARP S' (U+1E9E)](http://www.fileformat.info/info/unicode/char/1e9e/index.htm)? Because the letter you showed above is [Unicode Character 'LATIN SMALL LETTER SHARP S' (U+00DF)](http://www.fileformat.info/info/unicode/char/00df/index.htm) and that is included in Hack. There are also multiple discussions around the web mentioning that the `U+1E9E` isn't part of any modern language and can only be found in historical books. Read the comments on `U+00DF`, where it states that the uppercase version of `ß` is `SS` and that `U+1E9E` is non-standard.

**Comment by Bogbo** [comment] 2017-02-21 20:15
Thank you for your answer! I was actually meaning 1E9E, but couldn't enter this letter here. It's right that 1E9E is not part of the official German orthography but ß is replaced by SS in uppercase. The problem is uppercase spelling of surnames. E.g. Weiß und Weiss are both common surnames in German speaking countries. In uppercase without 1E9E they would both be spelled as WEISS which can lead to confusion. Hence I would appreciate a lot if "Hack" had 1E9E.

**Comment by chrissimpkins** [comment] 2017-06-28 14:41
Noted!

**Comment by funkyfuture** [comment] 2017-08-15 19:02
this is a duplicate of #164.

>  can only be found in historical books.

luckily there are efforts to make these books available via the web; and it'd be great to edit the sources with this wonderful font.

**Comment by chrissimpkins** [comment] 2017-10-20 01:38
Closing as duplicate of #164.  Let's discuss it there.

**Closed by chrissimpkins** 2017-10-20 01:38 UTC
Labels: Character Set, enhancement
