### ISSUE TITLE
Missing glyph for vim-airline

### ISSUE THREAD

**Issue by kylekthompson** [source-foundry/Hack#182] opened 2016-02-25 20:50 UTC
I'm running into an issue with a missing Line Number glyph in vim-airline. Here is a screenshot:

![screen shot 2016-02-25 at 3 48 58 pm](https://cloud.githubusercontent.com/assets/6563105/13333920/51f229f2-dbd7-11e5-8168-cc8380007cad.png)

I have noticed that if I open another buffer in vim, the inactive buffer correctly displays the line number glyph; however, the active buffer does not.

Let me know if you need anything else!

**Comment by kylekthompson** [comment] 2016-02-25 20:51
Actually, It looks like this is covered in #181. Sorry about that!

**Comment by chrissimpkins** [comment] 2016-02-25 21:50
did the fonts linked there fix this issue?

**Comment by kylekthompson** [comment] 2016-02-25 21:57
@chrissimpkins when I switch over to Fira Mono or Inconsolata (both patched for Powerline) the glyph is there

**Comment by kylekthompson** [comment] 2016-02-25 22:00
Also another note, patching your .otf fonts with [this](https://github.com/powerline/fontpatcher) fixes the glyph but messes up the sizing a little. See below:

![screen shot 2016-02-25 at 4 59 14 pm](https://cloud.githubusercontent.com/assets/6563105/13335865/3268ece2-dbe1-11e5-8e29-37bd6e6dc518.png)

![screen shot 2016-02-25 at 4 59 44 pm](https://cloud.githubusercontent.com/assets/6563105/13335870/367cc36c-dbe1-11e5-8329-a3d137b0f1f3.png)

![screen shot 2016-02-25 at 4 59 32 pm](https://cloud.githubusercontent.com/assets/6563105/13335871/36829ddc-dbe1-11e5-9d9a-0aa76f79a489.png)

**Comment by chrissimpkins** [comment] 2016-02-25 22:32
will reopen so that I can take a look at this.  reading on my phone and thought this was the issue with the Powerline glyphs in the bold set.  Thanks for poking me on this.   Let me have a look through both threads.

**Comment by kylekthompson** [comment] 2016-02-25 22:32
Sounds good. Thanks for checking it out! I love the font!

**Comment by chrissimpkins** [comment] 2016-02-25 22:53
Great to hear that! Thank you!

**Comment by chrissimpkins** [comment] 2016-02-26 14:10
@kylekthompson Have you tried that patch script with the ttf fonts instead of the otf builds?

**Comment by kylekthompson** [comment] 2016-02-26 14:42
Patched ttf fonts with both regular and non-ascii font size at 12pt (still a slight size issue):

![screen shot 2016-02-26 at 9 39 14 am](https://cloud.githubusercontent.com/assets/6563105/13355181/0d635d38-dc6d-11e5-8cba-1086626abca5.png)

Patched ttf fonts with regular font size at 12pt and non-ascii font size at 11pt (I can't notice a size issue on my non-retina display):

![screen shot 2016-02-26 at 9 39 57 am](https://cloud.githubusercontent.com/assets/6563105/13355202/2af711e6-dc6d-11e5-8fa4-cb2510e15574.png)

**Comment by kylekthompson** [comment] 2016-02-26 14:45
I also went ahead and bumped the non-ascii font size of the patched otf fonts down to 11 and the size difference can't be noticed with them either:

![screen shot 2016-02-26 at 9 45 37 am](https://cloud.githubusercontent.com/assets/6563105/13355315/b4600a32-dc6d-11e5-99f8-4d0fc2066b96.png)

**Comment by chrissimpkins** [comment] 2016-02-26 21:04
Let's take first issue as reported.  It looks to me like the active buffer is rendering the zero next to the line number Powerline glyph in bold.  Do you mind trying the development set of fonts in this directory to see if they fix this issue?  I patched the Powerline glyphs into the bold set and if this is the problem, it should be corrected (and these changes will be included with the next release).

https://github.com/chrissimpkins/Hack/tree/development/build/test_builds/DEV02172016

They should show up as test build v2.020 DEV02172016 when you install them.

**Comment by kylekthompson** [comment] 2016-02-26 21:13
The issue is not present in the dev dev builds :+1:

**Comment by chrissimpkins** [comment] 2016-02-26 21:14
Thanks for checking.  Does the alignment problem that you noticed change at all?

**Comment by kylekthompson** [comment] 2016-02-26 21:15
That still seems to be there.

![screen shot 2016-02-26 at 4 15 20 pm](https://cloud.githubusercontent.com/assets/6563105/13365634/26aed88a-dca4-11e5-8e1e-6e5b70742f40.png)

**Comment by chrissimpkins** [comment] 2016-02-26 21:25
OK, there were no changes that should have led to a change with the vertical alignments.  We've gone round and round with this issue in other issue reports.  The problem is that the alignment differs by platform/renderer/editor combinations and, unfortunately across platforms, in completely opposite alignment directions (some align too high, some too low).  If you are seeing this at some sizes and not others, we are probably getting into the realm of hinting problems with the glyphs as well.  

Did you happen to notice that there is a difference in the alignment that you saw with the fonts that you patched with the patch script vs the test builds that you just installed?

**Comment by kylekthompson** [comment] 2016-02-26 21:47
I'm not sure if it is an alignment difference, but the glyphs themselves appear to be slightly different. I made a [gif of two screenshots](http://cdn.makeagif.com/media/2-26-2016/HjEmxb.gif) to emphasize the difference.

What looks to be the smaller glyphs are the ones from your dev build:
![screen shot 2016-02-26 at 4 40 16 pm](https://cloud.githubusercontent.com/assets/6563105/13366346/9faae18a-dca8-11e5-9cbb-a62d26be8df5.png)

The slighter bigger glyphs are from the script:
![screen shot 2016-02-26 at 4 40 34 pm](https://cloud.githubusercontent.com/assets/6563105/13366360/a9107afa-dca8-11e5-941d-13fca0a9b9cf.png)

**Comment by kylekthompson** [comment] 2016-02-26 21:58
I am going to be away from my computer until about 10:00PM EST. When I get back I can troubleshoot more if you'd like. If not, I am definitely not opposed to just using a slightly different size for my non-ascii font. I'm glad the glyph is fixed for the bold set!

**Comment by chrissimpkins** [comment] 2016-02-26 23:11
> I'm glad the glyph is fixed for the bold set!

^5!

No rush on this at all.  We can work on it next week again.  Does it appear to you that the arrow head position is about the same (slightly screen top relative to rest of the line alignment) in both the script patched and dev build versions?  Seems to be the case based upon your screenshots (from what I can tell).

**Comment by kylekthompson** [comment] 2016-02-27 03:48
@chrissimpkins Sorry for the delay. The position itself seems very similar. I believe that the bottom and top of the arrow seem to be anchored at the same place (just slightly too tall). The tip of the arrow looks like it stretches out in the version patched with the script. 

In my description the arrow locations would be the following:
![screen shot 2016-02-26 at 10 47 27 pm](https://cloud.githubusercontent.com/assets/6563105/13370615/16cca6f4-dcdb-11e5-81dc-5aebc0115a58.png)

**Comment by chrissimpkins** [comment] 2016-03-01 12:57
@kylekthompson thank you!

**Comment by faceleg** [comment] 2016-04-13 21:50
This issue can be "resolved" in iTerm2 by reducing the "non-ascii font" size by 1 point.

**Comment by chrissimpkins** [comment] 2016-04-19 19:54
@faceleg Thanks Michael!

**Comment by chrissimpkins** [comment] 2017-10-23 22:15
Powerline glyph updates in PR by @iamjamestl included in the v3.000 release.  Please update and let us know if this is still an issue for you.  Will close.  Please reopen for further discussion.

**Closed by chrissimpkins** 2017-10-23 22:15 UTC
Labels: Character Set, Rendering issue
