### ISSUE TITLE
Number 1 looks too much like an l letter

### ISSUE THREAD

**Issue by LeoNeeson** [source-foundry/Hack#43] opened 2015-08-31 07:20 UTC
The "l" letter is fine, but the "1" number may still lead to confusion, since is similar to the lowercase letter "L" in many fonts. To me, the "1" number must be like this: http://i.imgur.com/pHeeYIJ.png
![improved](https://cloud.githubusercontent.com/assets/13534864/9573729/130c6b3a-4f96-11e5-9f57-8a1443e111ea.png)

**Comment by chrissimpkins** [comment] 2015-08-31 11:38
Can you let me know what pixel size you are working at and the platform you are using this on?  Might be a hinting/instruction issue if the glyphs begin to look similar.

**Comment by LeoNeeson** [comment] 2015-09-01 04:46
I'm using the normal display size at 72 PPI "DPI", using a Mac OS system. But this it's not exactly about resolution/system configuration, it's more about design. What I'm trying to explain, is that any newcomer to your font, "may" confuse the number "1" (of your font), with the lowercase letter "L" (in many other fonts). I'm not saying that the "l" and "1" are identical in your font.

But that it's up to you (and the community), since there are a lot of fonts to choose. If you are happy with the current "1" number, great. I've reported this, because IMHO this is a problem to me, but I don't mean it's a problem to everyone. It would be great to hear the opinion of other people to see if they agree on this or not. It's a design choice, not a bug report.

**Comment by willfroning** [comment] 2015-09-01 04:58
I agree. When you see the "l" and "1" next to each other it's obvious which is which, but having a downward slope to the "nose" would more clearly define it's identity.

**Comment by chrissimpkins** [comment] 2015-09-01 12:24
Noted.  Will take a look at this.  Is there a size threshold where you notice that the problem begins?

**Comment by chrissimpkins** [comment] 2015-09-01 12:50
@LeoNeeson Point well taken.  I ask because I am working on the optimization of the TT instructions and wanted to see if there might be a way to optimize it as is.  To my eye in that image, the stroke height on the 'l' vs. '1' (taller 'l' glyph) and the curved tail vs. flat bottom serif look distinct.  The problem is that these nuances tend to disappear as we challenge the glyphs to fit the grid at smaller pixel sizes. Height differences generally disappear and curves may be rendered as flat in which case, it would look exactly like the 1.  I will take a look into this in more detail.

Let's leave this open for more discussion.

**Comment by chrissimpkins** [comment] 2015-10-10 14:24
Queued up to get started on this.  Will post some design examples in this thread if you are willing to participate as we improve on the shape.

**Comment by LeoNeeson** [comment] 2015-10-11 06:22
Okay, I'll be here to give my opinion.

**Comment by chrissimpkins** [comment] 2015-10-16 01:42
I am going to push this issue back a bit.  @burodepeper is analyzing a number of usability issues in the fonts and we are going to spend a bit more time on the evaluation of this glyph (and others) before we begin a new design.   Our hope is to apply a more rigorous, objective approach to these usability issues and we have a number of tools in various stages of planning and development to assist with this.  We will have a great deal more information about this once they are in place.  We are actively discussing this in Slack and will bring the conversation about the `1` vs. `l` to this thread when we begin the development of a new glyph style.  Will update here when more information is available and a proposed fix is available for your review.

**Comment by bkromhout** [comment] 2015-10-20 01:10
Came here from #103 and will be watching for updates to this. The original issue I had was actually with ```i``` vs ```l```, though I also agree with the ```1``` vs ```l``` discussion going on here. 

I'll refrain from further comment until the new approach is revealed that is mentioned in the above comment, but for continuity will add that I feel that the ```i``` looks too similar to ```l``` due to the bottom of the glyph being nearly identical.

Also notable from 103 is that these issues intensify when I'm using my 1080p external monitor (vs. the 15" retina display in my MBP).

**Comment by burodepeper** [comment] 2015-10-20 07:47
Hi everybody, 

As @chrissimpkins mentioned, I'm working on analyzing these issues and improvements. In the mean time, it would be **incredibly helpful** if you could supply us with screenshots of situations where any of the issues mentioned above actually hindered you.

Let me put it in a different context. I am not only analyzing the abstract visual difference between two characters; I am also analyzing them within their context. For instance, the `i` in the word `this` is less 'important' than the `i` in `var i = 0`.

I am curious to any situation where you had to look twice at a character, just to be sure, or where any such confusion caused an actual bug that you had been hunting for hours. And let me be the first to say that Hack isn't perfect, because it was I (in the voice of Severus Snape) who failed to see the difference between a `:` and a `;` in a simple piece of code in an environment without syntax highlighting, linting, or any useful error logging. And it is my goal to fix these issues in such contexts.

**Comment by tflo** [comment] 2017-10-20 09:29
I “discovered” Hack just recently and the similarity of `1` to `l` (as used in other fonts) was exactly the first thing I stumbled upon. @LeoNeeson’s [post](https://github.com/source-foundry/Hack/issues/43#issuecomment-136585141) describes the issue very well.

I admit that the problem has become less of an issue once my brain has adapted to the Hack glyphs, since the Hack-`1` is definitely distinguishable from the Hack-`l`. But, for example, when coming back from another (not Hack-using) editor/program to my Hack-using editor there is still a moment of confusion.

– Tom

**Comment by chrissimpkins** [comment] 2017-10-20 11:01
Slated for work in the next release.  Keep an eye out for it!  Will post info / images as work goes on.

**Comment by chrissimpkins** [comment] 2017-10-28 01:50
First iteration:

#### Large render of shape change
![one](https://user-images.githubusercontent.com/4249591/32130127-42b2074a-bb60-11e7-98bd-f0806ed0d639.png)

#### At small size
![one-small](https://user-images.githubusercontent.com/4249591/32130139-835984b2-bb60-11e7-84a2-245afde94e7b.png)

#### Shape vs. other numerals in set
![one-numbers](https://user-images.githubusercontent.com/4249591/32130140-866d5048-bb60-11e7-943a-33c02e64dfa2.png)

**Comment by LeoNeeson** [comment] 2017-10-28 03:55
Looks great, I like the new shape.

**Comment by haktrik** [comment] 2017-10-28 12:41
Yes, this 1 in this design looks much better. 👍

**Comment by chrissimpkins** [comment] 2017-10-28 12:44
@LeoNeeson @haktrik ty both for having a look.  I will finish the other three sets and then build fonts that we can test at actual source code size to make sure that we have the angle correct.  Will examine the hints as well to see if we need to modify anything with the change in shape.  Will post here when I have branch with the fonts available for download and testing.

**Comment by chrissimpkins** [comment] 2017-10-29 01:40
Here are the changes in all four sets as of https://github.com/source-foundry/Hack/commit/379b3ad6d34d52f882de255ecd62c73b21a8c621

![one-regular](https://user-images.githubusercontent.com/4249591/32140024-9567a634-bc28-11e7-905c-c720d67ccded.png)

![one-italic](https://user-images.githubusercontent.com/4249591/32140025-98e1e842-bc28-11e7-833f-d3482fe64290.png)

![one-bold](https://user-images.githubusercontent.com/4249591/32140026-9bf1dc22-bc28-11e7-8c85-db0a1756e492.png)

![one-bolditalic](https://user-images.githubusercontent.com/4249591/32140027-9e30fe00-bc28-11e7-853d-50079bd6ba16.png)

**Comment by chrissimpkins** [comment] 2017-10-29 02:13
See pull request https://github.com/source-foundry/Hack/pull/347 or a full description of changes and link to the testing files that you can use to confirm that these design changes address this problem.  Let's continue the conversation on the pull request thread for any necessary changes to the current state of the design.  Once we have an acceptable set of designs, I will evaluate the instruction sets, update as necessary, and we will plan to include these changes in the v3.001 release.

**Comment by chrissimpkins** [comment] 2017-10-29 03:13
Also added alternate numeral one styles that include these upper stroke changes without the bottom slab to the alt-hack repository if this works better for you.  

https://github.com/source-foundry/alt-hack/tree/master/glyphs/u0031-noslab

Compile instructions available on the README for that repository.

<img src="https://user-images.githubusercontent.com/4249591/32140350-f316cb0a-bc34-11e7-9705-72b1aae2c61d.png" height="60">

<img src="https://user-images.githubusercontent.com/4249591/32140354-f76d041c-bc34-11e7-9589-26d75f3fff85.png" height="60">

<img src="https://user-images.githubusercontent.com/4249591/32140356-fb2b5590-bc34-11e7-8140-6dac1ead0eb1.png" height="60">

<img src="https://user-images.githubusercontent.com/4249591/32140358-fdd2b856-bc34-11e7-9d7a-7ddd3bd922f4.png" height="60">

**Comment by haktrik** [comment] 2017-10-29 14:05
Thanks @chrissimpkins  for rapid amendments of these glyphs. I've already tested on my IDE's and its works perfectly as I was expected. It's clearly visible even on small font sizes. One issue I have only with Jetbrain editor. But you probably saw already this issue. Someone reported similar: 
![image](https://user-images.githubusercontent.com/32274737/32144498-01fec6c4-bcba-11e7-8094-1cd49e83468f.png)
It's strange output seemb be somehow offset character? When I'm pressed "1,2,3,4,5,6" I getting strange symbols. But when I've pressed '7' I'm getting 1, when 8 getting 2. But design of  1 itself look fine. 

ps. Alternative without slab look also cool,  I will try test it!
Great Job. Thanks

**Comment by chrissimpkins** [comment] 2017-10-29 14:10
@haktrik thanks! Will you please add this information about incorrect JetBrains renders in that thread and confirm there that this is on Windows?

Thanks again.

**Comment by chrissimpkins** [comment] 2017-11-02 03:08
these changes were merged into the `dev` branch in https://github.com/source-foundry/Hack/commit/9cb3c2daad50d6483b8dc5119f4ea8939799de7b and will be released in v3.001

**Comment by chrissimpkins** [comment] 2017-11-02 03:09
Thanks all for your suggestions and help with the review of the glyphs!

**Closed** 2017-11-12 16:22 UTC
Labels: Design, Usability
